sudo: required

language: python

services:
  - docker

before_install:
- docker build -t foresight-flask-app python-service/
- docker run -d --env APP_SETTINGS=testing --name foresight-app-test foresight-flask-app
- docker ps -a

script:
- docker exec foresight-app-test python3 test_app.py

after_script:
- docker rm -f foresight-app-test