sudo: required

language: python

services:
  - docker

before_install:
- docker build -t foresight-flask-app python-service/
- docker run -d --name app foresight-flask-app
- docker ps -a

script:
- docker exec app python3 -m unittest discover

after_script:
- docker rm -f app